version: "3.5"

services:
  app:
    container_name: ${APP_NAME}_app
    hostname: ${APP_NAME}_app
    env_file:
      - .env
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        DEBUG: ${DEBUG}
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        APP_NAME: ${APP_NAME}
    volumes:
      - ./:/var/www/${APP_NAME}:rw
    networks:
      - default
    depends_on:
      - postgres
  postgres:
    container_name: ${APP_NAME}_postgres
    env_file:
      - .env
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default
    ports:
      - "${POSTGRES_PORT:-0}:5432"
  nginx:
    container_name: ${APP_NAME}_nginx
    hostname: ${APP_NAME}_nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    volumes:
      - ./:/var/www/${APP_NAME}:rw
      - ./docker/nginx/nginx_dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    env_file:
      - .env
    ports:
      - "${NGINX_PORT:-0}:80"
    expose:
      - "80"
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    external: false
    name: ${NETWORK}