version: "3.5"

services:
  app:
    container_name: ${APP_NAME}_app
    hostname: ${APP_NAME}_app
    env_file:
      - .env
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        DEBUG: ${DEBUG}
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
    volumes:
      - ./:/var/www/${APP_NAME}:rw
    ports:
      - "${APP_SSH_PORT}:22"
  postgres:
    container_name: ${APP_NAME}_postgres
    env_file:
      - .env
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${DB_NAME}
  nginx:
    container_name: ${APP_NAME}_nginx
    hostname: ${APP_NAME}_nginx
    image: nginx:1.21.6-alpine
    volumes:
      - ./docker/nginx/vhosts:/etc/nginx/vhosts
      - ./:/var/www/${APP_NAME}:rw
      - ./docker/nginx/nginx_dev.conf:/etc/nginx/nginx.conf
      - ./docker/postgres/dump:/docker-entrypoint-initdb.d
    ports:
      - "${NGINX_PORT}:80"
    links:
      - app

volumes:
  pgdata:
