name: Main

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: 7.4
          version: 2
          command: update
      - name: Tests
        run:  php vendor/bin/codecept run
      - name: Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SURV_HOST }}
          username: ${{ secrets.SURV_USER }}
          key: ${{ secrets.SURV_SSH_KEY }}
          script: |
            cd /var/www/html/
            git pull
#            composer install || composer update
#            php yii migrate --interactive=0
