name: CI-composer-v1

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: 8.0
          version: 2
          command: composer update
      - name: Tests
        run:  php vendor/bin/codecept run
      - name: Update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SURV_HOST }}
          username: ${{ secrets.SURV_USER }}
          key: ${{ secrets.SURV_SSH_KEY }}
          script: |
            cd /var/www/html/
            git pull
            composer install
            # php yii migrate --interactive=0
