name: CI-composer-v1

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@master
        with:
          php_version: 7.4
          version: 2
      - name: Test
        run:  php vendor/bin/codecept run